version: '3.8'

services:
  myshop-frontend:
    build:
      context: ./myshop-admin-seller
      dockerfile: Dockerfile
    ports:
      - "3001:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - myshop-network

  myshop-backend:
    build:
      context: ./myshop-backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://user:password@db:5432/myshop
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - myshop-network

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=myshop
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - myshop-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites-available:/etc/nginx/sites-available
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - myshop-frontend
      - myshop-backend
    restart: unless-stopped
    networks:
      - myshop-network

volumes:
  postgres_data:

networks:
  myshop-network:
    driver: bridge